---
apiVersion: v1
kind: Secret
metadata:
  name: rhsummit23-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23JanusN/rhsummit23-gateway-gitops
